function wep_scr() {
	if(image_index>=1&&image_index<2){
		wepx=-2
		wepy=4
		if(dir==1){
			wepangle=10
		}else{
			wepangle=350
		}
	}else{
		if(image_index>=2&&image_index<3){
			wepx=-1
			wepy=4
			if(dir==1){
				wepangle=15
			}else{
				wepangle=345
			}
		}else{
			if(image_index>=3&&image_index<4){
				wepx=1
				wepy=3
				if(dir==1){
					wepangle=30
				}else{
					wepangle=330
				}
			}else{
				if(image_index>=4&&image_index<5){
					wepx=-2
					wepy=5
				if(dir==1){
					wepangle=10
				}else{
					wepangle=350
				}
				}else{
					if(image_index>=5&&image_index<6){
						wepx=-3
						wepy=4
						if(dir==1){
							wepangle=345
						}else{
							wepangle=15
						}
					}else{
						if(image_index>=6&&image_index<7){
							wepx=-2
							wepy=3
							if(dir==1){
								wepangle=330
							}else{
								wepangle=30
							}
						}else{
							if(image_index>=7&&image_index<8){
								wepx=-1
								wepy=5
								if(dir==1){
									wepangle=10
								}else{
									wepangle=350
								}
							}else{
								if(image_index>=8&&image_index<9){
									wepx=-1
									wepy=4
									if(dir==1){
										wepangle=45
									}else{
										wepangle=315
									}
								}else{
									if(image_index>=9&&image_index<10){
										wepx=-2
										wepy=4
										if(dir==1){
											wepangle=45
										}else{
											wepangle=315
										}
									}else{
										if(image_index>=10&&image_index<11){
											wepx=-3
											wepy=3
											if(dir==1){
												wepangle=45
											}else{
												wepangle=315
											}
										}else{
											if(image_index>=11&&image_index<12){
												wepx=-2
												wepy=4
												if(dir==1){
													wepangle=45
												}else{
													wepangle=315
												}
											}else{
												if(image_index>=12&&image_index<13){
													wepx=-1
													wepy=4
													if(dir==1){
														wepangle=10
													}else{
														wepangle=350
													}
												}else{
													if(image_index>=14&&image_index<15){
														wepx=2
														wepy=3
														if(dir==1){
															wepangle=10
														}else{
															wepangle=350
														}
													}else{

													}
												}
											}
										}
									}
								}
							}
						}
					}
				}
			}
		}
	}
	wepx-=1
	if(dir==1){

	}else{
	wepx=wepx*-1
	}


}
